//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4016
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.ResourceManagement.WebServices.WSTrust
{
    using System.Runtime.Serialization;


}



/*[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface SecurityTokenServiceChannel : SecurityTokenService, System.ServiceModel.IClientChannel
{
}
 */

